apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: {{ include "target-group-binding.fullname" .}}
  labels:
    {{- include "target-group-binding.labels" . | nindent 4 }}
spec:
  serviceRef:
    name: {{ .Values.service.name }}
    port: {{ .Values.service.port }}
  targetType: ip
  targetGroupARN: {{ .Values.targetGroupARN }}
  networking:
    ingress:
    - from:
      - securityGroup:
          groupID: {{ .Values.sourceSecurityGroupID }}
      ports:
      - protocol: TCP